### PR TITLE
Add host and Open URL link with all parameters

### PR DESCRIPTION
**Pull request by sergiu-popa**

### CODE REVIEW

**Comment by nixilla** [comment]
How would this work with POST, PUT requests?

**Comment by sergiu-popa** [comment]
I tried with POST and it's working. Why wouldn't work? (using Buzz client)

**Comment by nixilla** [comment]
When you click "Open URL" for POST request it will not work. As browser will issue GET request.

Could you change HTML/Twig in the way that it checks the HTTP method and only show "Open URL" if GET (and OPTIONS)?

On the other hand, if the method is other then GET, I would like to see a "Copy as curl command" link. Would it be possible?

P.S. Thanks for contribution

**Comment by sergiu-popa** [comment]
See latest commit. Instead of "Copy as cURL commands" link I added a new row (copying to clipboard it not that easy to include a button. GitHub uses ZeroClipboard, which uses Flash, thus a 3d-party library.

**Pull request merged**
